name: dahlia_shared
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.0.0-0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  animations: ^2.0.7
  collection: ^1.17.1
  dbus: ^0.7.8
  dsettings:
    git: https://github.com/dahliaos/dsettings
  flutter:
    sdk: flutter
  intl: ^0.18.0
  logging: ^1.1.1
  path: ^1.8.3
  shared_preferences: ^2.0.20
  
  yatl:
    git:
      url: https://github.com/HrX03/yatl
      path: yatl
  
  yatl_flutter:
    git:
      url: https://github.com/HrX03/yatl
      path: yatl_flutter
  
  yatl_gen:
    git:
      url: https://github.com/HrX03/yatl
      path: yatl_gen

  zenit_ui:
    git:
      url: https://github.com/dahliaOS/zenit_ui.git
      ref: Version-0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
